version: 2.1

update_bundler: &update_bundler
  run:
    name: update bundler
    command: gem update bundler

bundle_install: &bundle_install
  run:
    name: bundle install
    command: bundle update --bundler && bundle install --path vendor/bundle --jobs 4

restore_bundle_cache: &restore_bundle_cache
  restore_cache:
    key: cache-bundler-{{ checksum "Gemfile.lock" }}

wait_redis_service: &wait_redis_service
  run:
    name: wait for redis
    command: dockerize -wait tcp://127.0.0.1:6379 -timeout 1m

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - *restore_bundle_cache
      - *update_bundler
      - *bundle_install
      - save_cache:
          key: cache-bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  rubocop:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - *restore_bundle_cache
      - *update_bundler
      - *bundle_install
      - run: bundle exec rubocop
  rspec:
    docker:
      - image: circleci/ruby
      - image: redis
    steps:
      - checkout
      - *restore_bundle_cache
      - *update_bundler
      - *bundle_install
      - run: bundle exec rspec
workflows:
  version: 2.1
  rspec:
    jobs:
      - build
      - rubocop:
          requires: [build]
      - rspec:
          requires: [build]
